# Generated by Django 4.0.3 on 2022-11-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='robotData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postime', models.CharField(max_length=20, null=True)),
                ('robotPositionX', models.IntegerField()),
                ('robotPositionY', models.IntegerField()),
            ],
        ),
    ]
