# Generated by Django 4.0.3 on 2022-12-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_requestdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestDelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestPosition', models.IntegerField()),
                ('requestMethod', models.IntegerField()),
                ('requestTime', models.CharField(max_length=20, null=True)),
                ('referenceStatus', models.BooleanField()),
                ('referenceTime', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
