# Generated by Django 4.0.3 on 2022-12-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_requestdeldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdeldata',
            name='referenceStatus',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
