# Generated by Django 4.0.3 on 2022-12-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_requestdeldata_loadingreadytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdeldata',
            name='loadedTime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
