# Generated by Django 4.0.3 on 2022-12-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_requestdeldata_mtutime'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdeldata',
            name='URTime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
