# Generated by Django 4.0.3 on 2022-12-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_requestdeldata_uctime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdeldata',
            old_name='UCTime',
            new_name='DRTime',
        ),
    ]
