# Generated by Django 4.0.3 on 2022-12-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_uctime_requestdeldata_drtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdeldata',
            name='UMTime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
