# Generated by Django 4.0.3 on 2022-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_requestdeldata_umtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdeldata',
            name='FTime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
