# Generated by Django 4.0.3 on 2022-12-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_requestdeldata_ftime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdeldata',
            old_name='referenceTime',
            new_name='MSTime',
        ),
    ]
