# Generated by Django 4.0.3 on 2022-12-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_robotdata2_robotpositionx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotdata2',
            name='robotPositionX',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='robotdata2',
            name='robotPositionY',
            field=models.IntegerField(),
        ),
    ]
